package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * TedentryId generated by hbm2java
 */
public class TedentryId implements java.io.Serializable {

	private String teRouterId;
	private String teLinkIdAddr;
	private String teLocalId;
	private String teRemoteId;
	private String username;

	public TedentryId() {
	}

	public TedentryId(String teRouterId, String teLinkIdAddr, String teLocalId,
			String teRemoteId, String username) {
		this.teRouterId = teRouterId;
		this.teLinkIdAddr = teLinkIdAddr;
		this.teLocalId = teLocalId;
		this.teRemoteId = teRemoteId;
		this.username = username;
	}

	public String getTeRouterId() {
		return this.teRouterId;
	}

	public void setTeRouterId(String teRouterId) {
		this.teRouterId = teRouterId;
	}

	public String getTeLinkIdAddr() {
		return this.teLinkIdAddr;
	}

	public void setTeLinkIdAddr(String teLinkIdAddr) {
		this.teLinkIdAddr = teLinkIdAddr;
	}

	public String getTeLocalId() {
		return this.teLocalId;
	}

	public void setTeLocalId(String teLocalId) {
		this.teLocalId = teLocalId;
	}

	public String getTeRemoteId() {
		return this.teRemoteId;
	}

	public void setTeRemoteId(String teRemoteId) {
		this.teRemoteId = teRemoteId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TedentryId))
			return false;
		TedentryId castOther = (TedentryId) other;

		return ((this.getTeRouterId() == castOther.getTeRouterId()) || (this
				.getTeRouterId() != null && castOther.getTeRouterId() != null && this
				.getTeRouterId().equals(castOther.getTeRouterId())))
				&& ((this.getTeLinkIdAddr() == castOther.getTeLinkIdAddr()) || (this
						.getTeLinkIdAddr() != null
						&& castOther.getTeLinkIdAddr() != null && this
						.getTeLinkIdAddr().equals(castOther.getTeLinkIdAddr())))
				&& ((this.getTeLocalId() == castOther.getTeLocalId()) || (this
						.getTeLocalId() != null
						&& castOther.getTeLocalId() != null && this
						.getTeLocalId().equals(castOther.getTeLocalId())))
				&& ((this.getTeRemoteId() == castOther.getTeRemoteId()) || (this
						.getTeRemoteId() != null
						&& castOther.getTeRemoteId() != null && this
						.getTeRemoteId().equals(castOther.getTeRemoteId())))
				&& ((this.getUsername() == castOther.getUsername()) || (this
						.getUsername() != null
						&& castOther.getUsername() != null && this
						.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getTeRouterId() == null ? 0 : this.getTeRouterId()
						.hashCode());
		result = 37
				* result
				+ (getTeLinkIdAddr() == null ? 0 : this.getTeLinkIdAddr()
						.hashCode());
		result = 37 * result
				+ (getTeLocalId() == null ? 0 : this.getTeLocalId().hashCode());
		result = 37
				* result
				+ (getTeRemoteId() == null ? 0 : this.getTeRemoteId()
						.hashCode());
		result = 37 * result
				+ (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
