package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * Tedentry generated by hbm2java
 */
public class Tedentry implements java.io.Serializable {

	private TedentryId id;
	private Integer teLinkStateId;
	private Integer teAreaId;
	private Integer teLinkInformationSource;
	private String teLinkInformationData;
	private Integer teLinkType;
	private Integer teMetric;
	private Long teMaxBandwidth;
	private Long teMaxReservableBandwidth;
	private Long teUnreservedBandwidthPri0;
	private Long teUnreservedbandwidthPri1;
	private Long teUnreservedbandwidthPri2;
	private Long teUnreservedbandwidthPri3;
	private Long teUnreservedbandwidthPri4;
	private Long teUnreservedbandwidthPri5;
	private Long teUnreservedbandwidthPri6;
	private Long teUnreservedbandwidthPri7;
	private Integer teAdministrativeGroup;
	private Integer teCost;
	private Integer telinkProtectonType;

	public Tedentry() {
	}

	public Tedentry(TedentryId id) {
		this.id = id;
	}

	public Tedentry(TedentryId id, Integer teLinkStateId, Integer teAreaId,
			Integer teLinkInformationSource, String teLinkInformationData,
			Integer teLinkType, Integer teMetric, Long teMaxBandwidth,
			Long teMaxReservableBandwidth, Long teUnreservedBandwidthPri0,
			Long teUnreservedbandwidthPri1, Long teUnreservedbandwidthPri2,
			Long teUnreservedbandwidthPri3, Long teUnreservedbandwidthPri4,
			Long teUnreservedbandwidthPri5, Long teUnreservedbandwidthPri6,
			Long teUnreservedbandwidthPri7, Integer teAdministrativeGroup,
			Integer teCost, Integer telinkProtectonType) {
		this.id = id;
		this.teLinkStateId = teLinkStateId;
		this.teAreaId = teAreaId;
		this.teLinkInformationSource = teLinkInformationSource;
		this.teLinkInformationData = teLinkInformationData;
		this.teLinkType = teLinkType;
		this.teMetric = teMetric;
		this.teMaxBandwidth = teMaxBandwidth;
		this.teMaxReservableBandwidth = teMaxReservableBandwidth;
		this.teUnreservedBandwidthPri0 = teUnreservedBandwidthPri0;
		this.teUnreservedbandwidthPri1 = teUnreservedbandwidthPri1;
		this.teUnreservedbandwidthPri2 = teUnreservedbandwidthPri2;
		this.teUnreservedbandwidthPri3 = teUnreservedbandwidthPri3;
		this.teUnreservedbandwidthPri4 = teUnreservedbandwidthPri4;
		this.teUnreservedbandwidthPri5 = teUnreservedbandwidthPri5;
		this.teUnreservedbandwidthPri6 = teUnreservedbandwidthPri6;
		this.teUnreservedbandwidthPri7 = teUnreservedbandwidthPri7;
		this.teAdministrativeGroup = teAdministrativeGroup;
		this.teCost = teCost;
		this.telinkProtectonType = telinkProtectonType;
	}

	public TedentryId getId() {
		return this.id;
	}

	public void setId(TedentryId id) {
		this.id = id;
	}

	public Integer getTeLinkStateId() {
		return this.teLinkStateId;
	}

	public void setTeLinkStateId(Integer teLinkStateId) {
		this.teLinkStateId = teLinkStateId;
	}

	public Integer getTeAreaId() {
		return this.teAreaId;
	}

	public void setTeAreaId(Integer teAreaId) {
		this.teAreaId = teAreaId;
	}

	public Integer getTeLinkInformationSource() {
		return this.teLinkInformationSource;
	}

	public void setTeLinkInformationSource(Integer teLinkInformationSource) {
		this.teLinkInformationSource = teLinkInformationSource;
	}

	public String getTeLinkInformationData() {
		return this.teLinkInformationData;
	}

	public void setTeLinkInformationData(String teLinkInformationData) {
		this.teLinkInformationData = teLinkInformationData;
	}

	public Integer getTeLinkType() {
		return this.teLinkType;
	}

	public void setTeLinkType(Integer teLinkType) {
		this.teLinkType = teLinkType;
	}

	public Integer getTeMetric() {
		return this.teMetric;
	}

	public void setTeMetric(Integer teMetric) {
		this.teMetric = teMetric;
	}

	public Long getTeMaxBandwidth() {
		return this.teMaxBandwidth;
	}

	public void setTeMaxBandwidth(Long teMaxBandwidth) {
		this.teMaxBandwidth = teMaxBandwidth;
	}

	public Long getTeMaxReservableBandwidth() {
		return this.teMaxReservableBandwidth;
	}

	public void setTeMaxReservableBandwidth(Long teMaxReservableBandwidth) {
		this.teMaxReservableBandwidth = teMaxReservableBandwidth;
	}

	public Long getTeUnreservedBandwidthPri0() {
		return this.teUnreservedBandwidthPri0;
	}

	public void setTeUnreservedBandwidthPri0(Long teUnreservedBandwidthPri0) {
		this.teUnreservedBandwidthPri0 = teUnreservedBandwidthPri0;
	}

	public Long getTeUnreservedbandwidthPri1() {
		return this.teUnreservedbandwidthPri1;
	}

	public void setTeUnreservedbandwidthPri1(Long teUnreservedbandwidthPri1) {
		this.teUnreservedbandwidthPri1 = teUnreservedbandwidthPri1;
	}

	public Long getTeUnreservedbandwidthPri2() {
		return this.teUnreservedbandwidthPri2;
	}

	public void setTeUnreservedbandwidthPri2(Long teUnreservedbandwidthPri2) {
		this.teUnreservedbandwidthPri2 = teUnreservedbandwidthPri2;
	}

	public Long getTeUnreservedbandwidthPri3() {
		return this.teUnreservedbandwidthPri3;
	}

	public void setTeUnreservedbandwidthPri3(Long teUnreservedbandwidthPri3) {
		this.teUnreservedbandwidthPri3 = teUnreservedbandwidthPri3;
	}

	public Long getTeUnreservedbandwidthPri4() {
		return this.teUnreservedbandwidthPri4;
	}

	public void setTeUnreservedbandwidthPri4(Long teUnreservedbandwidthPri4) {
		this.teUnreservedbandwidthPri4 = teUnreservedbandwidthPri4;
	}

	public Long getTeUnreservedbandwidthPri5() {
		return this.teUnreservedbandwidthPri5;
	}

	public void setTeUnreservedbandwidthPri5(Long teUnreservedbandwidthPri5) {
		this.teUnreservedbandwidthPri5 = teUnreservedbandwidthPri5;
	}

	public Long getTeUnreservedbandwidthPri6() {
		return this.teUnreservedbandwidthPri6;
	}

	public void setTeUnreservedbandwidthPri6(Long teUnreservedbandwidthPri6) {
		this.teUnreservedbandwidthPri6 = teUnreservedbandwidthPri6;
	}

	public Long getTeUnreservedbandwidthPri7() {
		return this.teUnreservedbandwidthPri7;
	}

	public void setTeUnreservedbandwidthPri7(Long teUnreservedbandwidthPri7) {
		this.teUnreservedbandwidthPri7 = teUnreservedbandwidthPri7;
	}

	public Integer getTeAdministrativeGroup() {
		return this.teAdministrativeGroup;
	}

	public void setTeAdministrativeGroup(Integer teAdministrativeGroup) {
		this.teAdministrativeGroup = teAdministrativeGroup;
	}

	public Integer getTeCost() {
		return this.teCost;
	}

	public void setTeCost(Integer teCost) {
		this.teCost = teCost;
	}

	public Integer getTelinkProtectonType() {
		return this.telinkProtectonType;
	}

	public void setTelinkProtectonType(Integer telinkProtectonType) {
		this.telinkProtectonType = telinkProtectonType;
	}

}
