package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * Hop generated by hbm2java
 */
public class Hop implements java.io.Serializable {

	private HopId id;
	private int mplsTunnelHopAddrType;
	private String mplsTunnelHopIpv4addr;
	private String mplsTunnelHopUnnumIfId;
	private Integer mplsTunnelHopIpv4prefixLen;
	private Long mplsTunnelHopIpv6addr;
	private Integer mplsTunnelHopIpv6prefixlen;
	private Integer mplsTunnelHopAsNumber;
	private Integer mplsTunnelHopLspId;
	private Integer mplsTunnelHopType;
	private Integer mplsTunnelHopIncluedeExclude;
	private String mplsTunnelHopPathOptionName;
	private Integer mplsTunnelHopEntryPathComp;
	private Integer mplsTunnelHopRowStatus;
	private Integer mplsTunnelHopStorageType;
	private Long mplsTunnelHopUnnumIfRouterId;
	private Integer mplsTunnelHopUseExplicitLabel;
	private Integer mplsTunnelHopExplictLabelType;
	private Integer mplsTunnelHopExplictLabel;
	private Integer mplsTunnelHopUseRevPathExpLbl;
	private Integer mplsTunnelHopRevPathExpLblType;
	private Integer mplsTunnelHopRevPathExpLbl;

	public Hop() {
	}

	public Hop(HopId id, int mplsTunnelHopAddrType,
			String mplsTunnelHopIpv4addr, String mplsTunnelHopUnnumIfId) {
		this.id = id;
		this.mplsTunnelHopAddrType = mplsTunnelHopAddrType;
		this.mplsTunnelHopIpv4addr = mplsTunnelHopIpv4addr;
		this.mplsTunnelHopUnnumIfId = mplsTunnelHopUnnumIfId;
	}

	public Hop(HopId id, int mplsTunnelHopAddrType,
			String mplsTunnelHopIpv4addr, String mplsTunnelHopUnnumIfId,
			Integer mplsTunnelHopIpv4prefixLen, Long mplsTunnelHopIpv6addr,
			Integer mplsTunnelHopIpv6prefixlen, Integer mplsTunnelHopAsNumber,
			Integer mplsTunnelHopLspId, Integer mplsTunnelHopType,
			Integer mplsTunnelHopIncluedeExclude,
			String mplsTunnelHopPathOptionName,
			Integer mplsTunnelHopEntryPathComp, Integer mplsTunnelHopRowStatus,
			Integer mplsTunnelHopStorageType,
			Long mplsTunnelHopUnnumIfRouterId,
			Integer mplsTunnelHopUseExplicitLabel,
			Integer mplsTunnelHopExplictLabelType,
			Integer mplsTunnelHopExplictLabel,
			Integer mplsTunnelHopUseRevPathExpLbl,
			Integer mplsTunnelHopRevPathExpLblType,
			Integer mplsTunnelHopRevPathExpLbl) {
		this.id = id;
		this.mplsTunnelHopAddrType = mplsTunnelHopAddrType;
		this.mplsTunnelHopIpv4addr = mplsTunnelHopIpv4addr;
		this.mplsTunnelHopUnnumIfId = mplsTunnelHopUnnumIfId;
		this.mplsTunnelHopIpv4prefixLen = mplsTunnelHopIpv4prefixLen;
		this.mplsTunnelHopIpv6addr = mplsTunnelHopIpv6addr;
		this.mplsTunnelHopIpv6prefixlen = mplsTunnelHopIpv6prefixlen;
		this.mplsTunnelHopAsNumber = mplsTunnelHopAsNumber;
		this.mplsTunnelHopLspId = mplsTunnelHopLspId;
		this.mplsTunnelHopType = mplsTunnelHopType;
		this.mplsTunnelHopIncluedeExclude = mplsTunnelHopIncluedeExclude;
		this.mplsTunnelHopPathOptionName = mplsTunnelHopPathOptionName;
		this.mplsTunnelHopEntryPathComp = mplsTunnelHopEntryPathComp;
		this.mplsTunnelHopRowStatus = mplsTunnelHopRowStatus;
		this.mplsTunnelHopStorageType = mplsTunnelHopStorageType;
		this.mplsTunnelHopUnnumIfRouterId = mplsTunnelHopUnnumIfRouterId;
		this.mplsTunnelHopUseExplicitLabel = mplsTunnelHopUseExplicitLabel;
		this.mplsTunnelHopExplictLabelType = mplsTunnelHopExplictLabelType;
		this.mplsTunnelHopExplictLabel = mplsTunnelHopExplictLabel;
		this.mplsTunnelHopUseRevPathExpLbl = mplsTunnelHopUseRevPathExpLbl;
		this.mplsTunnelHopRevPathExpLblType = mplsTunnelHopRevPathExpLblType;
		this.mplsTunnelHopRevPathExpLbl = mplsTunnelHopRevPathExpLbl;
	}

	public HopId getId() {
		return this.id;
	}

	public void setId(HopId id) {
		this.id = id;
	}

	public int getMplsTunnelHopAddrType() {
		return this.mplsTunnelHopAddrType;
	}

	public void setMplsTunnelHopAddrType(int mplsTunnelHopAddrType) {
		this.mplsTunnelHopAddrType = mplsTunnelHopAddrType;
	}

	public String getMplsTunnelHopIpv4addr() {
		return this.mplsTunnelHopIpv4addr;
	}

	public void setMplsTunnelHopIpv4addr(String mplsTunnelHopIpv4addr) {
		this.mplsTunnelHopIpv4addr = mplsTunnelHopIpv4addr;
	}

	public String getMplsTunnelHopUnnumIfId() {
		return this.mplsTunnelHopUnnumIfId;
	}

	public void setMplsTunnelHopUnnumIfId(String mplsTunnelHopUnnumIfId) {
		this.mplsTunnelHopUnnumIfId = mplsTunnelHopUnnumIfId;
	}

	public Integer getMplsTunnelHopIpv4prefixLen() {
		return this.mplsTunnelHopIpv4prefixLen;
	}

	public void setMplsTunnelHopIpv4prefixLen(Integer mplsTunnelHopIpv4prefixLen) {
		this.mplsTunnelHopIpv4prefixLen = mplsTunnelHopIpv4prefixLen;
	}

	public Long getMplsTunnelHopIpv6addr() {
		return this.mplsTunnelHopIpv6addr;
	}

	public void setMplsTunnelHopIpv6addr(Long mplsTunnelHopIpv6addr) {
		this.mplsTunnelHopIpv6addr = mplsTunnelHopIpv6addr;
	}

	public Integer getMplsTunnelHopIpv6prefixlen() {
		return this.mplsTunnelHopIpv6prefixlen;
	}

	public void setMplsTunnelHopIpv6prefixlen(Integer mplsTunnelHopIpv6prefixlen) {
		this.mplsTunnelHopIpv6prefixlen = mplsTunnelHopIpv6prefixlen;
	}

	public Integer getMplsTunnelHopAsNumber() {
		return this.mplsTunnelHopAsNumber;
	}

	public void setMplsTunnelHopAsNumber(Integer mplsTunnelHopAsNumber) {
		this.mplsTunnelHopAsNumber = mplsTunnelHopAsNumber;
	}

	public Integer getMplsTunnelHopLspId() {
		return this.mplsTunnelHopLspId;
	}

	public void setMplsTunnelHopLspId(Integer mplsTunnelHopLspId) {
		this.mplsTunnelHopLspId = mplsTunnelHopLspId;
	}

	public Integer getMplsTunnelHopType() {
		return this.mplsTunnelHopType;
	}

	public void setMplsTunnelHopType(Integer mplsTunnelHopType) {
		this.mplsTunnelHopType = mplsTunnelHopType;
	}

	public Integer getMplsTunnelHopIncluedeExclude() {
		return this.mplsTunnelHopIncluedeExclude;
	}

	public void setMplsTunnelHopIncluedeExclude(
			Integer mplsTunnelHopIncluedeExclude) {
		this.mplsTunnelHopIncluedeExclude = mplsTunnelHopIncluedeExclude;
	}

	public String getMplsTunnelHopPathOptionName() {
		return this.mplsTunnelHopPathOptionName;
	}

	public void setMplsTunnelHopPathOptionName(
			String mplsTunnelHopPathOptionName) {
		this.mplsTunnelHopPathOptionName = mplsTunnelHopPathOptionName;
	}

	public Integer getMplsTunnelHopEntryPathComp() {
		return this.mplsTunnelHopEntryPathComp;
	}

	public void setMplsTunnelHopEntryPathComp(Integer mplsTunnelHopEntryPathComp) {
		this.mplsTunnelHopEntryPathComp = mplsTunnelHopEntryPathComp;
	}

	public Integer getMplsTunnelHopRowStatus() {
		return this.mplsTunnelHopRowStatus;
	}

	public void setMplsTunnelHopRowStatus(Integer mplsTunnelHopRowStatus) {
		this.mplsTunnelHopRowStatus = mplsTunnelHopRowStatus;
	}

	public Integer getMplsTunnelHopStorageType() {
		return this.mplsTunnelHopStorageType;
	}

	public void setMplsTunnelHopStorageType(Integer mplsTunnelHopStorageType) {
		this.mplsTunnelHopStorageType = mplsTunnelHopStorageType;
	}

	public Long getMplsTunnelHopUnnumIfRouterId() {
		return this.mplsTunnelHopUnnumIfRouterId;
	}

	public void setMplsTunnelHopUnnumIfRouterId(
			Long mplsTunnelHopUnnumIfRouterId) {
		this.mplsTunnelHopUnnumIfRouterId = mplsTunnelHopUnnumIfRouterId;
	}

	public Integer getMplsTunnelHopUseExplicitLabel() {
		return this.mplsTunnelHopUseExplicitLabel;
	}

	public void setMplsTunnelHopUseExplicitLabel(
			Integer mplsTunnelHopUseExplicitLabel) {
		this.mplsTunnelHopUseExplicitLabel = mplsTunnelHopUseExplicitLabel;
	}

	public Integer getMplsTunnelHopExplictLabelType() {
		return this.mplsTunnelHopExplictLabelType;
	}

	public void setMplsTunnelHopExplictLabelType(
			Integer mplsTunnelHopExplictLabelType) {
		this.mplsTunnelHopExplictLabelType = mplsTunnelHopExplictLabelType;
	}

	public Integer getMplsTunnelHopExplictLabel() {
		return this.mplsTunnelHopExplictLabel;
	}

	public void setMplsTunnelHopExplictLabel(Integer mplsTunnelHopExplictLabel) {
		this.mplsTunnelHopExplictLabel = mplsTunnelHopExplictLabel;
	}

	public Integer getMplsTunnelHopUseRevPathExpLbl() {
		return this.mplsTunnelHopUseRevPathExpLbl;
	}

	public void setMplsTunnelHopUseRevPathExpLbl(
			Integer mplsTunnelHopUseRevPathExpLbl) {
		this.mplsTunnelHopUseRevPathExpLbl = mplsTunnelHopUseRevPathExpLbl;
	}

	public Integer getMplsTunnelHopRevPathExpLblType() {
		return this.mplsTunnelHopRevPathExpLblType;
	}

	public void setMplsTunnelHopRevPathExpLblType(
			Integer mplsTunnelHopRevPathExpLblType) {
		this.mplsTunnelHopRevPathExpLblType = mplsTunnelHopRevPathExpLblType;
	}

	public Integer getMplsTunnelHopRevPathExpLbl() {
		return this.mplsTunnelHopRevPathExpLbl;
	}

	public void setMplsTunnelHopRevPathExpLbl(Integer mplsTunnelHopRevPathExpLbl) {
		this.mplsTunnelHopRevPathExpLbl = mplsTunnelHopRevPathExpLbl;
	}

}
