package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * LoginUser generated by hbm2java
 */
public class LoginUser implements java.io.Serializable {

	private String username;
	private String password;

	public LoginUser() {
	}

	public LoginUser(String username) {
		this.username = username;
	}

	public LoginUser(String username, String password) {
		this.username = username;
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
