package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * HopId generated by hbm2java
 */
public class HopId implements java.io.Serializable {

	private int mplsTunnelHopListIndex;
	private int mplsTunnelHopPathOptionIndex;
	private int mplsTunnelHopIndex;

	public HopId() {
	}

	public HopId(int mplsTunnelHopListIndex, int mplsTunnelHopPathOptionIndex,
			int mplsTunnelHopIndex) {
		this.mplsTunnelHopListIndex = mplsTunnelHopListIndex;
		this.mplsTunnelHopPathOptionIndex = mplsTunnelHopPathOptionIndex;
		this.mplsTunnelHopIndex = mplsTunnelHopIndex;
	}

	public int getMplsTunnelHopListIndex() {
		return this.mplsTunnelHopListIndex;
	}

	public void setMplsTunnelHopListIndex(int mplsTunnelHopListIndex) {
		this.mplsTunnelHopListIndex = mplsTunnelHopListIndex;
	}

	public int getMplsTunnelHopPathOptionIndex() {
		return this.mplsTunnelHopPathOptionIndex;
	}

	public void setMplsTunnelHopPathOptionIndex(int mplsTunnelHopPathOptionIndex) {
		this.mplsTunnelHopPathOptionIndex = mplsTunnelHopPathOptionIndex;
	}

	public int getMplsTunnelHopIndex() {
		return this.mplsTunnelHopIndex;
	}

	public void setMplsTunnelHopIndex(int mplsTunnelHopIndex) {
		this.mplsTunnelHopIndex = mplsTunnelHopIndex;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HopId))
			return false;
		HopId castOther = (HopId) other;

		return (this.getMplsTunnelHopListIndex() == castOther
				.getMplsTunnelHopListIndex())
				&& (this.getMplsTunnelHopPathOptionIndex() == castOther
						.getMplsTunnelHopPathOptionIndex())
				&& (this.getMplsTunnelHopIndex() == castOther
						.getMplsTunnelHopIndex());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMplsTunnelHopListIndex();
		result = 37 * result + this.getMplsTunnelHopPathOptionIndex();
		result = 37 * result + this.getMplsTunnelHopIndex();
		return result;
	}

}
