package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * Trareq generated by hbm2java
 */
public class Trareq implements java.io.Serializable {

	private TrareqId id;
	private int setupPrio;
	private long bandwidth;
	private Integer includeAnyAffinity;
	private Integer includeAllAffinity;
	private Integer excludeAnyAffinity;
	private Integer maximumHopmount;
	private Integer protection;
	private Integer switchingType;
	private int operatestate;
	private Integer hoptableindex;
	private Integer encodingType;

	public Trareq() {
	}

	public Trareq(TrareqId id, int setupPrio, long bandwidth, int operatestate) {
		this.id = id;
		this.setupPrio = setupPrio;
		this.bandwidth = bandwidth;
		this.operatestate = operatestate;
	}

	public Trareq(TrareqId id, int setupPrio, long bandwidth,
			Integer includeAnyAffinity, Integer includeAllAffinity,
			Integer excludeAnyAffinity, Integer maximumHopmount,
			Integer protection, Integer switchingType, int operatestate,
			Integer hoptableindex, Integer encodingType) {
		this.id = id;
		this.setupPrio = setupPrio;
		this.bandwidth = bandwidth;
		this.includeAnyAffinity = includeAnyAffinity;
		this.includeAllAffinity = includeAllAffinity;
		this.excludeAnyAffinity = excludeAnyAffinity;
		this.maximumHopmount = maximumHopmount;
		this.protection = protection;
		this.switchingType = switchingType;
		this.operatestate = operatestate;
		this.hoptableindex = hoptableindex;
		this.encodingType = encodingType;
	}

	public TrareqId getId() {
		return this.id;
	}

	public void setId(TrareqId id) {
		this.id = id;
	}

	public int getSetupPrio() {
		return this.setupPrio;
	}

	public void setSetupPrio(int setupPrio) {
		this.setupPrio = setupPrio;
	}

	public long getBandwidth() {
		return this.bandwidth;
	}

	public void setBandwidth(long bandwidth) {
		this.bandwidth = bandwidth;
	}

	public Integer getIncludeAnyAffinity() {
		return this.includeAnyAffinity;
	}

	public void setIncludeAnyAffinity(Integer includeAnyAffinity) {
		this.includeAnyAffinity = includeAnyAffinity;
	}

	public Integer getIncludeAllAffinity() {
		return this.includeAllAffinity;
	}

	public void setIncludeAllAffinity(Integer includeAllAffinity) {
		this.includeAllAffinity = includeAllAffinity;
	}

	public Integer getExcludeAnyAffinity() {
		return this.excludeAnyAffinity;
	}

	public void setExcludeAnyAffinity(Integer excludeAnyAffinity) {
		this.excludeAnyAffinity = excludeAnyAffinity;
	}

	public Integer getMaximumHopmount() {
		return this.maximumHopmount;
	}

	public void setMaximumHopmount(Integer maximumHopmount) {
		this.maximumHopmount = maximumHopmount;
	}

	public Integer getProtection() {
		return this.protection;
	}

	public void setProtection(Integer protection) {
		this.protection = protection;
	}

	public Integer getSwitchingType() {
		return this.switchingType;
	}

	public void setSwitchingType(Integer switchingType) {
		this.switchingType = switchingType;
	}

	public int getOperatestate() {
		return this.operatestate;
	}

	public void setOperatestate(int operatestate) {
		this.operatestate = operatestate;
	}

	public Integer getHoptableindex() {
		return this.hoptableindex;
	}

	public void setHoptableindex(Integer hoptableindex) {
		this.hoptableindex = hoptableindex;
	}

	public Integer getEncodingType() {
		return this.encodingType;
	}

	public void setEncodingType(Integer encodingType) {
		this.encodingType = encodingType;
	}

}
