package dao;

// Generated 2011-3-12 17:33:56 by Hibernate Tools 3.4.0.CR1

/**
 * TrareqId generated by hbm2java
 */
public class TrareqId implements java.io.Serializable {

	private int mplsTunnelIndex;
	private int mplsTunnelInstance;
	private String ingressLsrid;
	private String egressLsrid;

	public TrareqId() {
	}

	public TrareqId(int mplsTunnelIndex, int mplsTunnelInstance,
			String ingressLsrid, String egressLsrid) {
		this.mplsTunnelIndex = mplsTunnelIndex;
		this.mplsTunnelInstance = mplsTunnelInstance;
		this.ingressLsrid = ingressLsrid;
		this.egressLsrid = egressLsrid;
	}

	public int getMplsTunnelIndex() {
		return this.mplsTunnelIndex;
	}

	public void setMplsTunnelIndex(int mplsTunnelIndex) {
		this.mplsTunnelIndex = mplsTunnelIndex;
	}

	public int getMplsTunnelInstance() {
		return this.mplsTunnelInstance;
	}

	public void setMplsTunnelInstance(int mplsTunnelInstance) {
		this.mplsTunnelInstance = mplsTunnelInstance;
	}

	public String getIngressLsrid() {
		return this.ingressLsrid;
	}

	public void setIngressLsrid(String ingressLsrid) {
		this.ingressLsrid = ingressLsrid;
	}

	public String getEgressLsrid() {
		return this.egressLsrid;
	}

	public void setEgressLsrid(String egressLsrid) {
		this.egressLsrid = egressLsrid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrareqId))
			return false;
		TrareqId castOther = (TrareqId) other;

		return (this.getMplsTunnelIndex() == castOther.getMplsTunnelIndex())
				&& (this.getMplsTunnelInstance() == castOther
						.getMplsTunnelInstance())
				&& ((this.getIngressLsrid() == castOther.getIngressLsrid()) || (this
						.getIngressLsrid() != null
						&& castOther.getIngressLsrid() != null && this
						.getIngressLsrid().equals(castOther.getIngressLsrid())))
				&& ((this.getEgressLsrid() == castOther.getEgressLsrid()) || (this
						.getEgressLsrid() != null
						&& castOther.getEgressLsrid() != null && this
						.getEgressLsrid().equals(castOther.getEgressLsrid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMplsTunnelIndex();
		result = 37 * result + this.getMplsTunnelInstance();
		result = 37
				* result
				+ (getIngressLsrid() == null ? 0 : this.getIngressLsrid()
						.hashCode());
		result = 37
				* result
				+ (getEgressLsrid() == null ? 0 : this.getEgressLsrid()
						.hashCode());
		return result;
	}

}
